### ISSUE TITLE
Game crashing when opening video settings.

### ISSUE THREAD

**Issue by zjavierf** [anviaan/SodiumExtraInformation#3] opened 2024-08-28 22:08 UTC
When using this mod with the new updates of sodium and sodium extra it crashes the game.

To reproduce the issue:
1)Use these versions
  - Sodium mc1.21.-0.6.0-beta.1-fabric
  -Sodium Extra mc1.21.1-0.6.0-beta.1+fabric
  -Sodium Extra Information 1.0
  -Reeses Sodium Options m1.21.1-1.8.0-beta.2+fabric
  
2) Launch Minecraft and press video settings
3) Game Crashes

**Comment by An-m1654** [comment] 2024-08-29 01:31
Is this a duplicate of #2?

**Closed as completed** 2024-09-01 00:15 UTC
